# Generated by Django 3.1.5 on 2021-01-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_of_ingredient', models.CharField(choices=[('veg', 'vegetable'), ('ft', 'fruit'), ('mt', 'meat'), ('fh', 'fish'), ('dy', 'diary'), ('egg', 'eggs'), ('or', 'other')], default='or', max_length=255)),
                ('cal_in_100_grams', models.IntegerField()),
                ('carb_in_100_grams', models.FloatField()),
                ('protein_in_100_grams', models.FloatField()),
                ('fat_in_100_grams', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('prep_time', models.CharField(max_length=30)),
                ('amount_of_calories', models.IntegerField()),
                ('describe', models.TextField()),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[('0', 'horrible'), ('1', 'disgusting'), ('2', 'definitely not good'), ('3', 'not so bad'), ('4', 'really good'), ('5', 'astonish')], default='0', max_length=255)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.recipe')),
            ],
        ),
    ]
